### ISSUE TITLE
More verbose output/stepping into the execution

### ISSUE THREAD

**Issue by adrienmaillard** [NASA-AMMOS/aerie-ts-user-code-runner#31]
I am trying to debug a TS code that is passed to the code runner but I can't find why the error would happen. Any chance that we could get a more verbose output ? 

Alternatively, would it be possible to attach some debugger to step in the execution directly ?

**Comment by camargo** [comment]
@jdylanstewart Any info here would be a huge help

**Comment by adrienmaillard** [comment]
I attached a debugger to the ts-code-runner and it is supposed to give us the stack as part of the error but we receive just a very small part of the stack. Still looking at it.

**Comment by dyst5422** [comment]
The stack returned is intentionally limited to the user code files [here](https://github.com/NASA-AMMOS/aerie-ts-user-code-runner/blob/develop/src/UserCodeRunner.ts#L360-L385) as those are the only parts our users can do anything about (any errors outside of that should either be caught in the type checking phase, or is an error in our code). It might be good to add logging of the entire stack though. You should be able to get the entire stack via the debugger too though.

**Comment by adrienmaillard** [comment]
Ok, somehow the error returned has `message` and `incomplete` stack fields that are the ones being json-inified. But the real `stack` is in a sub-object `error` field that is not defined by the user error class... it is weird. To access it, I have to use the object as an `any`.

**Comment by adrienmaillard** [comment]
Anyway, that's some postprocessing that can be done on aerie's side. Thank you !
